version: '3'

services:
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    # Entrypoint installs python dependencies if needed.
    entrypoint: ./docker-entrypoint.sh
    command: flask run
    # command: /bin/bash -c "sleep infinity & wait"
    volumes:
      - ./backend:/src
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: /src/app/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_CONFIG: local
      SQLALCHEMY_DATABASE_URI: 'postgresql://testuser:testpw@postgresql:5432/forum'
      SQLALCHEMY_TEST_DATABASE_URI: 'postgresql://testuser:testpw@postgresql:5432/forumtest'

  frontend:
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/src
    ports:
      - "8080:8080"
    command: npm run serve

  postgresql:
    image: postgres:11.2
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpw
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgresql:/var/lib/postgresql/data
