version: 2
jobs:
  build1: # job name
    docker: # Specifies the primary container image,
    # see circleci.com/docs/2.0/circleci-images/ for
    # the list of pre-built CircleCI images on dockerhub.
      - image: circleci/python:3.7.1

      - image: postgres:9.6.11 # Specifies the database image
       # for the secondary or service container run in a common
       # network where ports exposed on the primary container are
       # available on localhost.
        environment: # Specifies the POSTGRES_USER authentication
         # environment variable, see circleci.com/docs/2.0/env-vars/
         # for instructions about using environment variables.
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: forumtest

    steps:
      - checkout
      - run: cd backend && pytest

  build2: # job name
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/app
    steps:
      - checkout
      - run: cd frontend && yarn install
      - run: cd frontend && yarn test:unit

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build1
      - build2
